---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp:
  labels:
    app: aws-example-octodex
  name: aws-example-octodex
  namespace: development
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.podinfod: semver:~1.3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-example-octodex
  strategy: {}
  template:
    metadata:
      creationTimestamp:
      labels:
        app: aws-example-octodex
    spec:
      containers:
      - image: 204415123180.dkr.ecr.us-east-1.amazonaws.com/podman:aaf04d638e92c5a08238862faba29ff47a7e83e5
        name: aws-example-octodex
        imagePullPolicy: Always
        resources: {}
        ports:
        - containerPort: 5000
status: {}
