---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp:
  labels:
    app: aws-example-octodex
  name: aws-example-octodex
  namespace: development
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.podinfod: semver:~1.3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-example-octodex
  strategy: {}
  template:
    metadata:
      creationTimestamp:
      labels:
        app: aws-example-octodex
    spec:
      containers:
      - image: 204415123180.dkr.ecr.us-east-1.amazonaws.com/podman:63a177bb7cce533b2154122d2859765b42f89efc
        name: aws-example-octodex
        imagePullPolicy: Always
        resources: {}
        ports:
        - containerPort: 5000
status: {}
