apiVersion: v1
kind: Service
metadata:
  name: aws-example-octodex
  namespace: development
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: aws-example-octodex
